doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - zeusproject/templates
  - zeusproject/_module
  - zeusproject/_template
python-targets:
  - 3
